server:
  application:
    name: Cloud Order Service dev

spring:
  application:
    name: Cloud-Order-Service-dev

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: order80