spring:
  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #config druid
    #连接池的设置
    druid:
      initial-size: 5 #初始化时建立物理连接的个数
      min-idle: 5  #最小连接池数量
      max-active: 200  #最大连接池数量 maxIdle已经不再使用
      max-wait: 60000 #获取连接时最大等待时间，单位毫秒
      test-while-idle: true #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      time-between-eviction-runs-millis: 60000 #既作为检测的间隔时间又作为testWhileIdel执行的依据
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x' #用来检测连接是否有效的sql 必须是一个查询语句（ mysql中为 select 'x'  oracle中为 select 1 from dual）
      test-on-borrow: false #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false  #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      #exception-sorter: true #当数据库抛出不可恢复的异常时,抛弃该连接
      #pool-prepared-statements: true  #是否缓存preparedStatement,mysql5.5+建议开启
      max-pool-prepared-statement-per-connection-size: 20  #当值大于0时poolPreparedStatements会自动修改为true
      filters: stat,wall #配置扩展插件
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
      #设置访问druid监控页的账号和密码,默认没有--放DrugConfig配置中
      #stat-view-servlet.login-username: admin
      #stat-view-servlet.login-password: admin

  servlet:
    multipart:
      max-file-size: -1 #设置单个文件的大小 -1表示不限制
      max-request-size: -1 #单次请求的文件的总大小 -1表示不限制
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8001
  tomcat:
    basedir: ./logs
    background-processor-delay: 30
    redirect-context-root: true
    uri-encoding: UTF-8
    accesslog:
      enabled: true #为true时，上面的日期格式才有意义，否则就是写在一个文件里了
      buffered: true
      directory: ./
      file-date-format: .yyyy-MM-dd
      #pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D ms'
      pattern: '%t %a %m %U %s %b %D ms'
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log

mybatis:
  # 指定sql映射文件位置
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


