server:
  application:
    name: Cloud Payment Service dev

spring:
  application:
    name: Cloud-Payment-Service-dev

  datasource:
    #   数据源基本配置
    url: jdbc:mysql://118.31.170.227:3306/yang_mscloud_dev?serverTimezone=GMT%2b8&useUnicode=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: yzq0214

  redis:
    database: 1
    host: 118.31.170.227
    pool: 6379
    password: yzq0214

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8002